### ISSUE TITLE
Adding a blog post for new authors

### ISSUE THREAD

**Issue by ayushp20** [sustainability-lab/sustainability-lab.github.io#11]
I wanted to know process for adding a new blog. I had to add a new blog about how me and my group members went about making a conda installer for nilmtk. 
I believe it would start with adding the new authors to _data/authors.yml and the markdown of my blog to _posts. Would be helpful to know if I'm missing something out.

**Comment by Rithwikksvr** [comment]
You are not missing anything. That is the procedure followed for putting up the blog posts
